### ISSUE TITLE
Okay new issues for Steam due to Nvidia 455.38

### ISSUE THREAD

**Issue by Redbatman89** [pop-os/nvidia-graphics-drivers#76] opened 2020-11-22 00:46 UTC
So many users are reporting issues with fossilize replay eating ram on CPU when doing background vulkan shaders running non stop. I think you guys need to make 440.100 as an option again as I believe its driver related. Check out these posts from the steam git hub. 

https://github.com/ValveSoftware/steam-for-linux/issues/7472

https://github.com/ValveSoftware/Fossilize/issues/84

**Comment by jacobgkau** [comment] 2020-11-23 15:28
Closing as a duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/66.

**Closed by jacobgkau** 2020-11-23 15:28 UTC
